apiVersion: v1
kind: Service
metadata:
  name: astrbot-service-nodeport
  namespace: astrbot-ns
  labels:
    app: astrbot-stack
spec:
  type: NodePort
  selector:
    app: astrbot-stack
  ports:
    - name: napcat-web
      port: 6099
      targetPort: 6099
      # nodePort: 30099 # Optional: Specify a fixed NodePort if needed, otherwise remove this line
    - name: astrbot-web
      port: 6185
      targetPort: 6185
      # nodePort: 30185 # Optional: Specify a fixed NodePort if needed, otherwise remove this line